services:
  app:
    image: pool-cal-app
    build: .
    container_name: pool-cal
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env.local
      - .sa.env
    environment:
      - NODE_ENV=production
      - AUTH_TRUST_HOST=http:/...3000
